#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App.Resource", IsApplication=true)]

namespace App
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int cardBackgroundColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int cardCornerRadius = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cardElevation = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cardMaxElevation = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int cardPreventCornerOverlap = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int cardUseCompatPadding = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int contentPadding = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public const int contentPaddingBottom = 2130771978;
			
			// aapt resource value: 0x7f010007
			public const int contentPaddingLeft = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int contentPaddingRight = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int contentPaddingTop = 2130771977;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int cardview_dark_background = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int cardview_light_background = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int cardview_shadow_end_color = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int cardview_shadow_start_color = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int my_blue = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int my_gray = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int my_green = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int my_purple = 2130968582;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int cardview_compat_inset_shadow = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int cardview_default_elevation = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int cardview_default_radius = 2131034114;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int border = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int calc_icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int labs_launcher_cast_shedow_icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int note_icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int note_importance_high_icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int note_importance_low_icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int note_importance_medium_icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int noteItem_icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int pipette_icon = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090028
			public const int add_note_action = 2131296296;
			
			// aapt resource value: 0x7f090019
			public const int blueSeekBar = 2131296281;
			
			// aapt resource value: 0x7f090012
			public const int button0 = 2131296274;
			
			// aapt resource value: 0x7f09000e
			public const int button1 = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int button2 = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int button3 = 2131296272;
			
			// aapt resource value: 0x7f090009
			public const int button4 = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int button5 = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int button6 = 2131296267;
			
			// aapt resource value: 0x7f090004
			public const int button7 = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int button8 = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int button9 = 2131296262;
			
			// aapt resource value: 0x7f09001b
			public const int calculatorBtn = 2131296283;
			
			// aapt resource value: 0x7f090013
			public const int clearButton = 2131296275;
			
			// aapt resource value: 0x7f09001a
			public const int colorPickerBtn = 2131296282;
			
			// aapt resource value: 0x7f090016
			public const int colorTextVeiw = 2131296278;
			
			// aapt resource value: 0x7f090024
			public const int creationDateTextView = 2131296292;
			
			// aapt resource value: 0x7f090020
			public const int detailsCreationDateTextView = 2131296288;
			
			// aapt resource value: 0x7f090022
			public const int detailsDescriptionTextView = 2131296290;
			
			// aapt resource value: 0x7f090021
			public const int detailsExpirationDateTextView = 2131296289;
			
			// aapt resource value: 0x7f09001d
			public const int detailsImportanceImageView = 2131296285;
			
			// aapt resource value: 0x7f09001e
			public const int detailsNameTextView = 2131296286;
			
			// aapt resource value: 0x7f090000
			public const int displayTextView = 2131296256;
			
			// aapt resource value: 0x7f090007
			public const int divideButton = 2131296263;
			
			// aapt resource value: 0x7f090014
			public const int equalityButton = 2131296276;
			
			// aapt resource value: 0x7f090001
			public const int errorTextView = 2131296257;
			
			// aapt resource value: 0x7f090018
			public const int greenSeekBar = 2131296280;
			
			// aapt resource value: 0x7f090023
			public const int iconImageView = 2131296291;
			
			// aapt resource value: 0x7f09001f
			public const int importanceImageView = 2131296287;
			
			// aapt resource value: 0x7f090011
			public const int minusButton = 2131296273;
			
			// aapt resource value: 0x7f09000c
			public const int multiplyButton = 2131296268;
			
			// aapt resource value: 0x7f090025
			public const int nameTextView = 2131296293;
			
			// aapt resource value: 0x7f09001c
			public const int notesBtn = 2131296284;
			
			// aapt resource value: 0x7f090026
			public const int notesListRecyclerView = 2131296294;
			
			// aapt resource value: 0x7f090015
			public const int plusButton = 2131296277;
			
			// aapt resource value: 0x7f090017
			public const int redSeekBar = 2131296279;
			
			// aapt resource value: 0x7f090027
			public const int search_action = 2131296295;
			
			// aapt resource value: 0x7f090002
			public const int tableLayout1 = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int tableRow1 = 2131296259;
			
			// aapt resource value: 0x7f090008
			public const int tableRow2 = 2131296264;
			
			// aapt resource value: 0x7f09000d
			public const int tableRow3 = 2131296269;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Calculator = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ColorPicker = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int NoteDetails = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int NoteItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Notes = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int action_bar = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070006
			public const int add_note = 2131165190;
			
			// aapt resource value: 0x7f070000
			public const int app_name = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int calculator_label = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int color_picker_label = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int creation_date = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int expiration_date = 2131165192;
			
			// aapt resource value: 0x7f070004
			public const int note_details = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int notes_label = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int search = 2131165189;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Base_CardView = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int CardView = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int CardView_Dark = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int CardView_Light = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int CardView_MyBlue = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int MyCustomTheme = 2131099652;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[] {
					16843071,
					16843072,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978};
			
			// aapt resource value: 1
			public const int CardView_android_minHeight = 1;
			
			// aapt resource value: 0
			public const int CardView_android_minWidth = 0;
			
			// aapt resource value: 2
			public const int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public const int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public const int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public const int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 7
			public const int CardView_cardPreventCornerOverlap = 7;
			
			// aapt resource value: 6
			public const int CardView_cardUseCompatPadding = 6;
			
			// aapt resource value: 8
			public const int CardView_contentPadding = 8;
			
			// aapt resource value: 12
			public const int CardView_contentPaddingBottom = 12;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingLeft = 9;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingRight = 10;
			
			// aapt resource value: 11
			public const int CardView_contentPaddingTop = 11;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
