#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NoteWidget.Resource", IsApplication=true)]

namespace NoteWidget
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int dark_blue = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int dark_gray = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int light_gray = 2131034114;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add_icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int event_note_icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int noteItem_icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int notes_collection_icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int sync_icon = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070004
			public const int addNoteIcon = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int noteNameTextView = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int notesListView = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int notesTitleTextView = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int syncNotesIcon = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int syncStatusTextView = 2131165187;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int NoteListItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Widget = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int not_synced_status = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int note_id_toast_message = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int notes_title = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int synced_status = 2131099651;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int Widget = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
